
addons:
  postgresql: "9.3"

before_script:
  - mysql -e 'create database increment_with_sql;'
  - psql -c 'create database increment_with_sql;' -U postgres

rvm:
  - 2.1.1
  - 2.3.3
  - jruby
env:
  - DATABASE=sqlite
  - DATABASE=mysql
  - DATABASE=postgres
matrix:
  allow_failures:
    - rvm: jruby

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.1.gemfile

install:
  - "travis_retry bundle install"

script: "bundle exec rake test"
sudo: false

